### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by saanasum** [bioinf-jku/panelcn.mops#1]
Hi,

when doing devtools::install_github("bioinf-jku/panelcn.mops")

the following error occurs: 

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server

How can I fix this issue? (install.packages("devtools") was successful). 

Thanks for your help.
s.

**Comment by gpovysil** [comment]
It seems like you have problems connecting to github. The following link might help:
http://stackoverflow.com/questions/39285570/error-in-curlcurl-fetch-memoryurl-handle-handle-couldnt-connect-to-ser

Alternatively you can download the package and install the zip directly in R without devtools.

**Comment by saanasum** [comment]
I tried:

`library(httr)`
`set_config(use_proxy(url="10.3.100.207",port=8080))`

now the error changed to:

`Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Timeout was reached`

According the alternative approach: When downloading the package as panelcn.mops-master.zip and installing it via tools --> Install packages, the following occurs:

`install.packages(".../panelcn.mops-master.zip", repos = NULL, type = "win.binary")
 `
--> I guess an error happened? Because when trying `library(panelcn.mops)` --> `Error in library(panelcn.mops) : es gibt kein Paket namens ‘panelcn.mops’`

![001](https://cloud.githubusercontent.com/assets/20478730/23562831/605c4da0-0044-11e7-8838-b49973b054a0.PNG)

**Comment by gpovysil** [comment]
You have to use:
install.packages("panelcn.mops-master.zip", repos = NULL, type="source")
since the zip is not a windows binary.

**Comment by saanasum** [comment]
same error: 

![002](https://cloud.githubusercontent.com/assets/20478730/23563173/d1aa0d0c-0045-11e7-830c-b0d3e35eae52.PNG)

**Comment by gpovysil** [comment]
Sorry, I responded too quickly and did not test it properly. You have to extract the folder within the zip and then install it with
install.packages("panelcn.mops-master", repos = NULL, type="source")

**Comment by saanasum** [comment]
Many thanks!!! 
Now it works. I will further test it on TSC-94 datasets with InDels in some genes on Monday. I am really excited if it’s going to detect the small InDels in some of those genes. 
Have a nice weekend!

**Comment by gpovysil** [comment]
You're welcome, I hope everything works.
