### ISSUE TITLE
Cannot use exon XXXX

### ISSUE THREAD

**Issue by Ismaelfermir** [bioinf-jku/panelcn.mops#10]
Hi! 

I am a Master student trying to use your tool panelcn.MOPS for detecting CNV from WES data and I had a problem. I put 16 test samples and 50 control samples and there is a problem in the _runPanelcnMops_ step because the tool said that can not use some exons. Why can not be included this exons in the analysis and how can I fix this problem for including all exons?

Thanks!

Ismael Fernandez

**Comment by gpovysil** [comment]
Sorry for the late response. This means these exons have low coverage or are very small and therefore did not exceed the minMedianRC threshold. By default the threshold is set to 30, if you want to include all simply set this threshold to 0.

**Comment by Ismaelfermir** [comment]
Perfect!

Thanks for the answer,

Ismael Fernandez
