### ISSUE TITLE
Output file!

### ISSUE THREAD

**Issue by Ismaelfermir** [bioinf-jku/panelcn.mops#11]
Hi!

I am a Master Thesis student working with your tool "panelcn.MOPS" for detecting CNVs in WES data for application in clinical genetic diagnosis. I have a question about the output CNVs table. My table has this format:

```
Sample | Gene | Exon | Start | End | RC | MedRC | RC.norm | MedRC.norm | LowQual | CN
1456 | SDF4 | SDF4 | 1155 | 1156 | 1489 | 1491 | 1742 | 1598 |   | CN2
2037 | HES4 | HES4 | 2589 | 2845 | 456 | 1142 | 401 | 840 | lowQual | CN0
```
With this format I am able to detecting a validation set of samples with CNVs when I know the position of the CNV but it is very difficult to detect a CNV in a sample when I do not know the position of the CNV or if the sample has a phatogenic CNV. It is also difficult to detect the exact position of the CNV when the output gives you all the regions of your bedfile in place to the CNVs with their breakpoints. 

My question is if there is some script or tool that give a better score than the CN0, CN1, CN2, CN3 and CN4 and the breakpoints of the CNVs.

Thanks!

Ismael

**Comment by gpovysil** [comment]
I'm not sure what you are looking for exactly. If you only want to see CNs different from 2 you can use:
resulttable[which(resulttable$CN != "CN2"| is.na(resulttable$CN)),]
