### ISSUE TITLE
maxControls parameter can't be set to 0 in runPanelcnMops

### ISSUE THREAD

**Issue by kietoparao** [bioinf-jku/panelcn.mops#14]
The `runPanelcnMops` documentation for `maxControls` parameter is the following:

> integer reflecting the maximal numbers of controls to use. If set to 0 all highly correlated controls are used. Default = 25

But if I try to set it 0, the execution fails with the following error:

> Error in panelcn.mops(subset(XandCB[, c(t, controli)], subsetIdx), testi = 1,  : 
>   "maxControls" must be numeric, larger than 0 and of length 1.

I solved it by simply setting it to the number of controls available with `maxControls=length(mcols(control))`, but I thought you would like to know about this issue.

Thanks for such a great tool! :)

**Comment by gpovysil** [comment]
Thanks for the info. The check should have been for >=0, it should be fixed now.
