### ISSUE TITLE
Problems with visualisation

### ISSUE THREAD

**Issue by fre335** [bioinf-jku/panelcn.mops#16]
Hello,

First of all thanks for developing panelcnMOPS, i obtain good results with low fp rates.
However i have a problem with the visualisation of the CNVs with the function: plotBoxplot

> plotBoxplot(result         =           resultlist[[1]],           sampleName           =    sampleNames[1]       	,countWindows           =           countWindows,selectedGenes           =           selectedGenes,           showGene           =   1 )

As an Error i get the following message:

Error in FUN(X[[i]], ...) : subscript out of bounds

The gen i want to have a look at was not excluded and is part of resultlist. 
Any idea what the problem could be?

thanks in advance!

**Comment by gpovysil** [comment]
Good to hear that you like panelcn.mops. Can you post more of your code e.g. how you generated the resultlist and what sampleNames and selectedGenes are?

**Comment by fre335** [comment]
Sure, here is my code:




library("panelcn.mops")

bed <- "*****hg38.bed"


countWindows           <-           getWindows(bed)


patientbam <-  "*******.bam"

patient <-         countBamListInGRanges(countWindows           =           countWindows,bam.files           =           patientbam,           read.width           =           150)



bamFile <- list.files("********", pattern = "*.bam$")

controlbam <- file.path("******", bamFile)


control <-  countBamListInGRanges(countWindows           =           countWindows,bam.files           =           controlbam,           read.width           =           150)

XandCB           <-   patient


selectedGenes = c("ANO5_ex1_UTR_ONLY" ,
                  "ANO5_ex1" ,
                  "ANO5_ex2" ,
                  "ANO5_ex3" ,
                  "ANO5_ex4" ,
                  "ANO5_ex5" ,
                  "ANO5_ex6" ,
                  "ANO5_ex7" ,
                  "ANO5_ex8" ,
                  "ANO5_ex9" ,
                  "ANO5_ex10" ,
                  "ANO5_ex11" ,
                  "ANO5_ex12" ,
                  "ANO5_ex13" ,
                  "ANO5_ex14" ,
                  "ANO5_ex15" ,
                  "ANO5_ex16" ,
                  "ANO5_ex17" ,
                  "ANO5_ex18" ,
                  "ANO5_ex19" ,
                  "ANO5_ex20" ,
                  "ANO5_ex21",
                  "ANO5_ex22" ,
                  "ANO5_ex22_UTR_ONLY")

elementMetadata(XandCB)           <-           cbind(elementMetadata(XandCB),elementMetadata(control))

resultlist           <-           runPanelcnMops(XandCB,           countWindows           =           countWindows,selectedGenes           =           selectedGenes  , sex= "mixed")

sampleNames           <-           colnames(elementMetadata(patient))

resulttable           <-           createResultTable(resultlist           =           resultlist,           XandCB           =           XandCB,countWindows           =           countWindows,selectedGenes           =           selectedGenes,sampleNames =       sampleNames)



print(colnames(elementMetadata(patient)))



plotBoxplot(result         =           resultlist[[1]],           sampleName           =    sampleNames[1]       	,countWindows           =           countWindows,selectedGenes           =           selectedGenes,           showGene           =   1 )

**Comment by gpovysil** [comment]
I notice that your selectedGenes are not genes, but actually exons. Do you have multiple windows/rows per exon in your countWindows?
Could you post head(countWindows)?

**Comment by fre335** [comment]
It is working fine now. I used a wrong bed.file, where Gene name and exon where tab seperated. 

Thanks a lot for your help!
