### ISSUE TITLE
Custom reference (control) data

### ISSUE THREAD

**Issue by saanasum** [bioinf-jku/panelcn.mops#2]
Hi, 

is there a way to use individual TSC-94 reference datasets as control (e.g. as *.bam files)? 

I am analyzing TSC-94 data from selected samples where array-CGH showed the deletion of selected exons from TSC-94 genes (array-CGH positive) which is mostly supported using panelcn.mops. However, there are a lot of false-positives and I would like to try wether this can be limited to a minimum when using own TSC-94 reference datasets (n=15) (array-CGH negative). 

Thanks for your help
s.

**Comment by saanasum** [comment]
I guess using this function:

`controlbams <- list.files(system.file(".../References/", package = "panelcn.mops"),
                      pattern = ".bam$", full.names = TRUE)`
`control <-  countBamListInGRanges(countWindows = countWindows,
                               bam.files = controlbams, read.width = 150)`

**Comment by gpovysil** [comment]
Of course you have to use your own control samples. The controls included in the package are not even panel samples, but whole exome samples from the 1000 Genomes project that I reduced to a selection of genes from the TSC panel. (You also have to use your own BED file for the same reason.)
You just have to use countBamListInGRanges() with a list of sample names (with absolute or relative paths to BAM files) to create your own control base. The more control samples you use, the more reliable the method gets. We recommend to use at least 8-10 controls.

**Comment by saanasum** [comment]
Thank you!
