### ISSUE TITLE
Using panelcn.mops for amplicon-based panel sequencing?

### ISSUE THREAD

**Issue by saanasum** [bioinf-jku/panelcn.mops#3]
Hi,

I was wondering wether it is possible to use panelcn.mops for amplicon-based panels like TST-15 or TST-26 panels. Would you suggest to use it or need major parameters to be changed when applying panelcn.mops to amplicon-based panel sequencing due to higher number of read counts and due to different mapping coverage graphs.

Thanks for your help
s.

**Comment by gpovysil** [comment]
We have not tried panelcn.MOPS with amplicon-based panels. I assume you would have to optimize at least the read counting (maybe set read.width = FALSE) and the parameters specified in Section 8 "Adjusting sensitivity and speciﬁcity" in the manual namely I and the normalization parameters.

However, I would be careful with the panels you mentioned. panelcn.MOPS has not been optimized for tumor samples and also if you only have a panel of 15 genes the normalization might not work as well as for larger panels.

**Comment by saanasum** [comment]
Ok. I will try it and let you know how it looks like.

**Comment by saanasum** [comment]
So far it is not convincing. However, we tried this on FFPE material and not on blood. Once we have tried this on blood I let you know.
