### ISSUE TITLE
Short explanation of the number after "CN"

### ISSUE THREAD

**Issue by saanasum** [bioinf-jku/panelcn.mops#4]
In the result table the column "CN" contains the "CN" plus a specific number. Could you please shortly comment on the meaning of the number after "CN". For example what is the difference between CN1 or CN2 or CN3  ... I guess it means 1 copy, 2 copies, 3 copies and so on ...

**Comment by gpovysil** [comment]
Exactly CN1 means copy number 1 (usually a deletion), CN2 is "normal" copy number 2 and a duplication will lead to copy number 3 (CN3).
