### ISSUE TITLE
devtools panelcn.mops installation fails

### ISSUE THREAD

**Issue by jmaggi** [bioinf-jku/panelcn.mops#5]
Hi, 

I am trying to install the panelcn.mops package onto a Windows machine on R (version 3.4.0). I installed the cn.mops package and devtools. However, when i try to install the panelcn.mops package, I get this error:

```
`> devtools::install_github("bioinf-jku/panelcn.mops")  
Downloading GitHub repo bioinf-jku/panelcn.mops@master
from URL https://api.github.com/repos/bioinf-jku/panelcn.mops/zipball/master
Installing panelcn.mops
"C:/Users/maggi/Documents/R/R-3.4.0/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/maggi/AppData/Local/Temp/RtmpcBi2Rj/devtools98c46022ea6/bioinf-jku-panelcn.mops-ffbdaf2"  \
  --library="C:/Users/maggi/Documents/R/R-3.4.0/library" --install-tests 

* installing *source* package 'panelcn.mops' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error: package or namespace load failed for 'GenomeInfoDb' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'GenomeInfoDbData'
Error : package 'GenomeInfoDb' could not be loaded
ERROR: lazy loading failed for package 'panelcn.mops'
* removing 'C:/Users/maggi/Documents/R/R-3.4.0/library/panelcn.mops'
Installation failed: Command failed (1)`
d for package 'panelcn.mops'
* removing 'C:/Users/maggi/Documents/R/R-3.4.0/library/panelcn.mops'
Installation failed: Command failed (1)`

```
Not sure what the problem is and how to fix it.

Thanks for your time.

**Comment by gpovysil** [comment]
Sorry for the inconvenience. I just tested the installation on a clean version of R 3.4.0 on Windows and it works fine. GenomeInfoDbData (which is missing in your case and causes the crash) should be automatically installed in the first step where you install cn.mops. However, you can also manually install it with

```
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("GenomeInfoDbData")
```
If additional packages were missing you would have to do the same. So you can either try and install cn.mops again with the latest BiocInstaller and see if it works or install the missing packages manually as described above.

**Comment by jmaggi** [comment]
@gpovysil Thanks. I just installed GenomeInfoDbData manually, and now it's all set for the analysis.
